[features]
seeds = false
skip-lint = false
[programs.devnet]
recurring_thread = "J73oVDeCpLvffqA2R6eGozL2N76ucod1LpEGdB22wneU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/nick619/.config/solana/id.json"

[scripts]
thread = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/recurring-thread.ts"
